[package]
name = "blobtest"
version = "0.1.0"
authors = ["Erik Moldtmann <erik.moldtmann@altow.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.sdl2]
features = ["image"]
version = "0.35.1"